module.exports = [
    {
        "domain": ".acloud.guru",
        "expirationDate": 1608071307,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__hssc",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "147374312.1.1608069507415",
        "id": 1
    },
    {
        "domain": ".acloud.guru",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__hssrc",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1",
        "id": 2
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1641765507,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__hstc",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "147374312.14fb3daa730af95bde229514effefbfb.1607803314816.1607994593731.1608069507415.16",
        "id": 3
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1615845509,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "fb.1.1607803315476.706547142",
        "id": 4
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1671141506,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.1956968487.1607803308",
        "id": 5
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1671062056,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_C2EG9YN04N",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1607989413.6.1.1607990056.60",
        "id": 6
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1615585701,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1532375199.1607809702",
        "id": 7
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1608155906,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.901090985.1607803308",
        "id": 8
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1671061716,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_mkto_trk",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "id:194-UHP-609&token:_mch-acloud.guru-1607821144485-93805",
        "id": 9
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1608076116,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetsid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "c1b31bb03cc311eb82dcb97d9455967f",
        "id": 10
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1609393716,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetvid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "c1b34cf03cc311eb934c25ba27a78c5f",
        "id": 11
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1639605509,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ajs_anonymous_id",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%22b8b37433-2d57-4541-8701-e17e50d192b5%22",
        "id": 12
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1639605509,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ajs_user_id",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%22auth0%7C5d89c4608de2380d5bce3d68%22",
        "id": 13
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1923429509,
        "hostOnly": false,
        "httpOnly": false,
        "name": "amplitude_id_31ff08719287b555cdb2e4f366e6ed63acloud.guru",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "eyJkZXZpY2VJZCI6IjMxNDdkY2E0LWRkODYtNDdkYS1hYThlLWMzMjgxOWI3YjEzM1IiLCJ1c2VySWQiOiJhdXRoMHw1ZDg5YzQ2MDhkZTIzODBkNWJjZTNkNjgiLCJvcHRPdXQiOmZhbHNlLCJzZXNzaW9uSWQiOjE2MDgwNjk1MDY2ODMsImxhc3RFdmVudFRpbWUiOjE2MDgwNjk1MDk5ODUsImV2ZW50SWQiOjM1NiwiaWRlbnRpZnlJZCI6ODIyLCJzZXF1ZW5jZU51bWJlciI6MTE3OH0=",
        "id": 14
    },
    {
        "domain": ".acloud.guru",
        "hostOnly": false,
        "httpOnly": false,
        "name": "amplitude_idundefinedacloud.guru",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "eyJvcHRPdXQiOmZhbHNlLCJzZXNzaW9uSWQiOm51bGwsImxhc3RFdmVudFRpbWUiOm51bGwsImV2ZW50SWQiOjAsImlkZW50aWZ5SWQiOjAsInNlcXVlbmNlTnVtYmVyIjowfQ==",
        "id": 15
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1641765507,
        "hostOnly": false,
        "httpOnly": false,
        "name": "hubspotutk",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "14fb3daa730af95bde229514effefbfb",
        "id": 16
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1623355319,
        "hostOnly": false,
        "httpOnly": false,
        "name": "optimizelyEndUserId",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "oeu1607803319201r0.11937358922396779",
        "id": 17
    },
    {
        "domain": ".acloud.guru",
        "expirationDate": 1671061716,
        "hostOnly": false,
        "httpOnly": false,
        "name": "trwv.uid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "acloudguru-1607809703214-eacb786c%3A6",
        "id": 18
    },
    {
        "domain": "learn.acloud.guru",
        "expirationDate": 1623355928,
        "hostOnly": true,
        "httpOnly": false,
        "name": "_ALGOLIA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "anonymous-bed437ab-97d4-4291-83e1-374fee58004f",
        "id": 19
    },
    {
        "domain": "learn.acloud.guru",
        "expirationDate": 1609279108,
        "hostOnly": true,
        "httpOnly": false,
        "name": "auth0_token",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFrUTJNRFpCTmpSRFJEbEVOemsxT1RNeU9EQTJRamt3UlVFM01FRkZNamN5TXpORU9VVkJOZyJ9.eyJodHRwczovL25zLmFjbG91ZC5ndXJ1L3JvbGVzIjp7Im1lbWJlciI6dHJ1ZSwiZW5oYW5jZWRTeWxsYWJ1cyI6ZmFsc2UsImZvcnVtV3JpdGVBY2Nlc3MiOnRydWV9LCJodHRwczovL25zLmFjbG91ZC5ndXJ1L3VzZXJDcmVhdGVkQXQiOiIyMDE5LTA5LTI0VDA3OjIzOjEzLjcyN1oiLCJpc3MiOiJodHRwczovL2F1dGguYWNsb3VkLmd1cnUvIiwic3ViIjoiYXV0aDB8NWQ4OWM0NjA4ZGUyMzgwZDViY2UzZDY4IiwiYXVkIjoiaHR0cHM6Ly9hY2xvdWRndXJ1LmF1dGgwLmNvbS9hcGkvdjIvIiwiaWF0IjoxNjA4MTYzODc1LCJleHAiOjE2MDgxNzEwNzUsImF6cCI6Ik9LRmc5dW9QTUNOZWx2bHZLVkRmUEs3NjZEUmRBWUQ1Iiwic2NvcGUiOiIifQ.qHao0ke2c-d2glxZbE380NJcDxLyEkF7-VxHSREy8VzaN3T0GoLeIZUgscefr1a-Egxqgk_tqQ6T0PkBWxg1AopglgqtqDlC-u1VQNqeDJwag22fQmbjqZkaNuxu3kvrcB1p8M13wl1XXdPocs-IVLQYgq4LIPXp8Fif4WcsuIDKWpGt73pg0AAxtKsPEkeIML-c2wa-k9qsLPi2AaqtNykL9n8wiwuZuitvX-gF0-ydxFUiofNMm4ulCwBqFZoyrpsjEqsed5NQgPYIYemKX4fM8R9ZOqxrtWXOzaxXp1SNI7x8iQMfIAaWLIdSUVcjjz_ziH4geaASyLI-OCagug",
        "id": 20
    }
];

